### PR TITLE
Do not remove the selection from input/textarea elements

### PR DESCRIPTION
**Pull request by yrucrem**
Admin please build this request.

### CODE REVIEW

**Comment by GenticsDev** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.office:8080//job/alohaeditor-upstream-pullrequests/326/<h2>Build result: FAILURE</span></h2>[...truncated 590 lines...]log4j:WARN Please initialize the log4j system properly.[INFO] [INFO] --- jslint4java-maven-plugin:2.0.2:lint (lint-core) @ alohaeditor ---[INFO] /opt/jenkins/.jenkins/jobs/alohaeditor-upstream-pullrequests/workspace/src/lib/aloha/selection.js:616:21: 'range' was used before it was defined.[INFO] 					range.select();[INFO]                     ^[INFO] ------------------------------------------------------------------------[INFO] BUILD FAILURE[INFO] ------------------------------------------------------------------------[INFO] Total time: 24:11.987s[INFO] Finished at: Wed Jul 29 14:21:36 CEST 2015[INFO] Final Memory: 86M/2936M[INFO] ------------------------------------------------------------------------Waiting for Jenkins to finish collecting data[ERROR] Failed to execute goal com.googlecode.jslint4java:jslint4java-maven-plugin:2.0.2:lint (lint-core) on project alohaeditor: JSLint found 1 problems in 42 files -> [Help 1][ERROR] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.[ERROR] Re-run Maven using the -X switch to enable full debug logging.[ERROR] [ERROR] For more information about the errors and possible solutions, please read the following articles:[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException[JENKINS] Archiving /opt/jenkins/.jenkins/jobs/alohaeditor-upstream-pullrequests/workspace/pom.xml to org.alohaeditor/alohaeditor/1.1.33-SNAPSHOT/alohaeditor-1.1.33-SNAPSHOT.pomchannel stoppedSetting status of df3edec6dfdbc4215afe2aaa2368cac9863c010a to FAILURE with url http://jenkins.office/job/alohaeditor-upstream-pullrequests/326/ and message: Build finished.
Test FAILed.

**Comment by GenticsDev** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.office:8080//job/alohaeditor-upstream-pullrequests/327/
Test PASSed.

**Comment by GenticsDev** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.office:8080//job/alohaeditor-upstream-pullrequests/328/<h2>Failed Tests: <span class='status-failure'>1</span></h2><h3><a name='alohaeditor-upstream-pullrequests/org.alohaeditor:alohaeditor' /><a href='http://jenkins.office/job/alohaeditor-upstream-pullrequests/328/org.alohaeditor$alohaeditor/testReport'>alohaeditor-upstream-pullrequests/org.alohaeditor:alohaeditor</a>: <span class='status-failure'>1</span></h3><ul><li><a href='http://jenkins.office/job/alohaeditor-upstream-pullrequests/328/org.alohaeditor$alohaeditor/testReport/[Query timeout tests (single repository)] - Test timeouts for Aloha.RepositoryManager.query method(com.gentics.testutils.maven.selenium.qunit/QUnitTest)/_Query_timeout_tests_/'><strong>[Query timeout tests (single repository)] - Test timeouts for Aloha.RepositoryManager.query method(com.gentics.testutils.maven.selenium.qunit.QUnitTest).[Query timeout tests </strong></a></li></ul>
Test FAILed.

**Comment by npomaroli** [comment]
Admin please build this request.

**Comment by GenticsDev** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.office:8080//job/alohaeditor-upstream-pullrequests/329/
Test PASSed.

**Pull request merged**
