### PR TITLE
Hotfix ff br white space

### PR DESCRIPTION
**Pull request by najor**

### CODE REVIEW

**Comment by berni2288** [comment]
Admin please build this request

**Comment by GenticsDev** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.office:8080//job/alohaeditor-upstream-pullrequests/285/
Test FAILed.

**Comment by GenticsDev** [comment]
Can one of the admins verify this patch?

**Comment by GenticsDev** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
