### PR TITLE
Fix inline elements not being deleted when deleting the text inside them

### PR DESCRIPTION
**Pull request by berni2288**
SUP-223

### CODE REVIEW

**Comment by GenticsDev** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.office:8080//job/alohaeditor-upstream-pullrequests/246/
Test FAILed.

**Comment by berni2288** [comment]
Can one of the admins verify this patch?

**Comment by berni2288** [comment]
@GenticsDev Please Test test

**Comment by GenticsDev** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.office:8080//job/alohaeditor-upstream-pullrequests/247/<h2>Build result: FAILURE</span></h2>[...truncated 639 lines...][INFO] 		if (isUnmodifiedAlohaEditingP(placeholder)) {[INFO]             ^[INFO] ------------------------------------------------------------------------[INFO] BUILD FAILURE[INFO] ------------------------------------------------------------------------[INFO] Total time: 26:46.221s[INFO] Finished at: Mon Feb 16 15:18:55 CET 2015[INFO] Final Memory: 75M/2950M[INFO] ------------------------------------------------------------------------Waiting for Jenkins to finish collecting data[ERROR] Failed to execute goal com.googlecode.jslint4java:jslint4java-maven-plugin:2.0.2:lint (lint-core) on project alohaeditor: JSLint found 8 problems in 40 files -> [Help 1][ERROR] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.[ERROR] Re-run Maven using the -X switch to enable full debug logging.[ERROR] [ERROR] For more information about the errors and possible solutions, please read the following articles:[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException[JENKINS] Archiving /opt/jenkins/.jenkins/jobs/alohaeditor-upstream-pullrequests/workspace/pom.xml to org.alohaeditor/alohaeditor/0.25.23-SNAPSHOT/alohaeditor-0.25.23-SNAPSHOT.pomchannel stoppedDeleting project workspace... doneSetting status of 29f7ab594ab1e8f91d2690ca42f6ad6d89725973 to FAILURE with url http://jenkins.office:8080/job/alohaeditor-upstream-pullrequests/247/ and message: Merged build finished.
Test FAILed.

**Comment by GenticsDev** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.office:8080//job/alohaeditor-upstream-pullrequests/248/<h2>Build result: FAILURE</span></h2>[...truncated 633 lines...][INFO] 		if (isUnmodifiedAlohaEditingP(placeholder)) {[INFO]             ^[INFO] ------------------------------------------------------------------------[INFO] BUILD FAILURE[INFO] ------------------------------------------------------------------------[INFO] Total time: 23:36.314s[INFO] Finished at: Mon Feb 16 15:56:36 CET 2015[INFO] Final Memory: 79M/2946M[INFO] ------------------------------------------------------------------------Waiting for Jenkins to finish collecting data[ERROR] Failed to execute goal com.googlecode.jslint4java:jslint4java-maven-plugin:2.0.2:lint (lint-core) on project alohaeditor: JSLint found 6 problems in 40 files -> [Help 1][ERROR] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.[ERROR] Re-run Maven using the -X switch to enable full debug logging.[ERROR] [ERROR] For more information about the errors and possible solutions, please read the following articles:[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException[JENKINS] Archiving /opt/jenkins/.jenkins/jobs/alohaeditor-upstream-pullrequests/workspace/pom.xml to org.alohaeditor/alohaeditor/0.25.23-SNAPSHOT/alohaeditor-0.25.23-SNAPSHOT.pomchannel stoppedDeleting project workspace... doneSetting status of 1893eaae4fbc49580ce6635eb57f08d04217a99d to FAILURE with url http://jenkins.office:8080/job/alohaeditor-upstream-pullrequests/248/ and message: Merged build finished.
Test FAILed.

**Comment by berni2288** [comment]
@GenticsDev Please Test test

**Comment by GenticsDev** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.office:8080//job/alohaeditor-upstream-pullrequests/249/
Test FAILed.

**Comment by berni2288** [comment]
@GenticsDev Please Test test

**Comment by GenticsDev** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.office:8080//job/alohaeditor-upstream-pullrequests/251/<h2>Build result: FAILURE</span></h2>[...truncated 628 lines...][INFO] 		if (isUnmodifiedAlohaEditingP(placeholder)) {[INFO]             ^[INFO] ------------------------------------------------------------------------[INFO] BUILD FAILURE[INFO] ------------------------------------------------------------------------[INFO] Total time: 42:52.235s[INFO] Finished at: Mon Feb 16 18:31:35 CET 2015[INFO] Final Memory: 80M/2951M[INFO] ------------------------------------------------------------------------Waiting for Jenkins to finish collecting data[ERROR] Failed to execute goal com.googlecode.jslint4java:jslint4java-maven-plugin:2.0.2:lint (lint-core) on project alohaeditor: JSLint found 6 problems in 40 files -> [Help 1][ERROR] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.[ERROR] Re-run Maven using the -X switch to enable full debug logging.[ERROR] [ERROR] For more information about the errors and possible solutions, please read the following articles:[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException[JENKINS] Archiving /opt/jenkins/.jenkins/jobs/alohaeditor-upstream-pullrequests/workspace/pom.xml to org.alohaeditor/alohaeditor/0.25.23-SNAPSHOT/alohaeditor-0.25.23-SNAPSHOT.pomchannel stoppedDeleting project workspace... doneSetting status of b264c18e5ce05df08a6f14311311462c125df7a1 to FAILURE with url http://jenkins.office:8080/job/alohaeditor-upstream-pullrequests/251/ and message: Merged build finished.
Test FAILed.

**Comment by GenticsDev** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.office:8080//job/alohaeditor-upstream-pullrequests/253/<h2>Build result: FAILURE</span></h2>[...truncated 616 lines...][INFO] 		if (isUnmodifiedAlohaEditingP(placeholder)) {[INFO]             ^[INFO] ------------------------------------------------------------------------[INFO] BUILD FAILURE[INFO] ------------------------------------------------------------------------[INFO] Total time: 23:12.215s[INFO] Finished at: Tue Feb 17 12:26:24 CET 2015[INFO] Final Memory: 81M/2950M[INFO] ------------------------------------------------------------------------Waiting for Jenkins to finish collecting data[ERROR] Failed to execute goal com.googlecode.jslint4java:jslint4java-maven-plugin:2.0.2:lint (lint-core) on project alohaeditor: JSLint found 6 problems in 40 files -> [Help 1][ERROR] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.[ERROR] Re-run Maven using the -X switch to enable full debug logging.[ERROR] [ERROR] For more information about the errors and possible solutions, please read the following articles:[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException[JENKINS] Archiving /opt/jenkins/.jenkins/jobs/alohaeditor-upstream-pullrequests/workspace/pom.xml to org.alohaeditor/alohaeditor/0.25.23-SNAPSHOT/alohaeditor-0.25.23-SNAPSHOT.pomchannel stoppedDeleting project workspace... doneSetting status of a33dafb91e743b996757447aff23631ec1337cba to FAILURE with url http://jenkins.office:8080/job/alohaeditor-upstream-pullrequests/253/ and message: Merged build finished.
Test FAILed.

**Comment by berni2288** [comment]
@GenticsDev Please Test test

**Comment by GenticsDev** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.office:8080//job/alohaeditor-upstream-pullrequests/255/
Test FAILed.

**Comment by berni2288** [comment]
@GenticsDev Please Test test

**Comment by GenticsDev** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.office:8080//job/alohaeditor-upstream-pullrequests/256/
Test PASSed.

**Comment by GenticsDev** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.office:8080//job/alohaeditor-upstream-pullrequests/257/
Test FAILed.

**Pull request merged**
