### PR TITLE
Fix weird drag'n'drop behaviour with blocks in IE

### PR DESCRIPTION
**Pull request by npomaroli**

### CODE REVIEW

**Comment by GenticsDev** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.office:8080//job/alohaeditor-upstream-pullrequests/273/
Test PASSed.

**Comment by GenticsDev** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.office:8080//job/alohaeditor-upstream-pullrequests/274/<h2>Failed Tests: <span class='status-failure'>1</span></h2><h3><a name='org.alohaeditor:alohaeditor' /><a href='http://jenkins.office/job/alohaeditor-upstream-pullrequests/274/org.alohaeditor$alohaeditor/testReport'>org.alohaeditor:alohaeditor</a>: <span class='status-failure'>1</span></h3><ul><li><a href='http://jenkins.office/job/alohaeditor-upstream-pullrequests/274/org.alohaeditor$alohaeditor/testReport/[Query timeout tests (single repository)] - Test timeouts for Aloha.RepositoryManager.query method(com.gentics.testutils.maven.selenium.qunit/QUnitTest)/_Query_timeout_tests_/'><strong>[Query timeout tests (single repository)] - Test timeouts for Aloha.RepositoryManager.query method(com.gentics.testutils.maven.selenium.qunit.QUnitTest).[Query timeout tests </strong></a></li></ul>
Test FAILed.

**Comment by GenticsDev** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.office:8080//job/alohaeditor-upstream-pullrequests/275/<h2>Failed Tests: <span class='status-failure'>3</span></h2><h3><a name='org.alohaeditor:alohaeditor' /><a href='http://jenkins.office/job/alohaeditor-upstream-pullrequests/275/org.alohaeditor$alohaeditor/testReport'>org.alohaeditor:alohaeditor</a>: <span class='status-failure'>3</span></h3><ul><li><a href='http://jenkins.office/job/alohaeditor-upstream-pullrequests/275/org.alohaeditor$alohaeditor/testReport/com.gentics.testutils.maven.selenium.qunit/QUnitTest/_bold_29______foo_span_contenteditable_false__bar____span_baz____u2192____b__foo_span_contenteditable_false_bar___span_baz____b___/'><strong>com.gentics.testutils.maven.selenium.qunit.QUnitTest.[bold 29] - \"foo<span contenteditable=false>[bar]<\/span>baz\" \u2192 \"<b>[foo<span contenteditable=false>bar<\/span>baz]<\/b>\"</strong></a></li><li><a href='http://jenkins.office/job/alohaeditor-upstream-pullrequests/275/org.alohaeditor$alohaeditor/testReport/com.gentics.testutils.maven.selenium.qunit/QUnitTest/_bold_31______foo_span_contenteditable_false_ba_r____span_baz____u2192____b__foo_span_contenteditable_false_bar___span_baz____b___/'><strong>com.gentics.testutils.maven.selenium.qunit.QUnitTest.[bold 31] - \"foo<span contenteditable=false>ba[r]<\/span>baz\" \u2192 \"<b>[foo<span contenteditable=false>bar<\/span>baz]<\/b>\"</strong></a></li><li><a href='http://jenkins.office/job/alohaeditor-upstream-pullrequests/275/org.alohaeditor$alohaeditor/testReport/com.gentics.testutils.maven.selenium.qunit/QUnitTest/_bold_32______fo_o_span_contenteditable_false_b_ar___span_baz____u2192___fo__b_o____b__span_contenteditable_false_bar___span_baz__/'><strong>com.gentics.testutils.maven.selenium.qunit.QUnitTest.[bold 32] - \"fo[o<span contenteditable=false>b]ar<\/span>baz\" \u2192 \"fo[<b>o]<\/b><span contenteditable=false>bar<\/span>baz\"</strong></a></li></ul>
Test FAILed.

**Comment by Jotschi** [comment]
@GenticsDev please test

**Comment by GenticsDev** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.office:8080//job/alohaeditor-upstream-pullrequests/279/<h2>Failed Tests: <span class='status-failure'>4</span></h2><h3><a name='org.alohaeditor:alohaeditor' /><a href='http://jenkins.office/job/alohaeditor-upstream-pullrequests/279/org.alohaeditor$alohaeditor/testReport'>org.alohaeditor:alohaeditor</a>: <span class='status-failure'>4</span></h3><ul><li><a href='http://jenkins.office/job/alohaeditor-upstream-pullrequests/279/org.alohaeditor$alohaeditor/testReport/com.gentics.testutils.maven.selenium.qunit/QUnitTest/_bold_29______foo_span_contenteditable_false__bar____span_baz____u2192____b__foo_span_contenteditable_false_bar___span_baz____b___/'><strong>com.gentics.testutils.maven.selenium.qunit.QUnitTest.[bold 29] - \"foo<span contenteditable=false>[bar]<\/span>baz\" \u2192 \"<b>[foo<span contenteditable=false>bar<\/span>baz]<\/b>\"</strong></a></li><li><a href='http://jenkins.office/job/alohaeditor-upstream-pullrequests/279/org.alohaeditor$alohaeditor/testReport/com.gentics.testutils.maven.selenium.qunit/QUnitTest/_bold_31______foo_span_contenteditable_false_ba_r____span_baz____u2192____b__foo_span_contenteditable_false_bar___span_baz____b___/'><strong>com.gentics.testutils.maven.selenium.qunit.QUnitTest.[bold 31] - \"foo<span contenteditable=false>ba[r]<\/span>baz\" \u2192 \"<b>[foo<span contenteditable=false>bar<\/span>baz]<\/b>\"</strong></a></li><li><a href='http://jenkins.office/job/alohaeditor-upstream-pullrequests/279/org.alohaeditor$alohaeditor/testReport/com.gentics.testutils.maven.selenium.qunit/QUnitTest/_bold_32______fo_o_span_contenteditable_false_b_ar___span_baz____u2192___fo__b_o____b__span_contenteditable_false_bar___span_baz__/'><strong>com.gentics.testutils.maven.selenium.qunit.QUnitTest.[bold 32] - \"fo[o<span contenteditable=false>b]ar<\/span>baz\" \u2192 \"fo[<b>o]<\/b><span contenteditable=false>bar<\/span>baz\"</strong></a></li><li><a href='http://jenkins.office/job/alohaeditor-upstream-pullrequests/279/org.alohaeditor$alohaeditor/testReport/[Query timeout tests (single repository)] - Test timeouts for Aloha.RepositoryManager.query method(com.gentics.testutils.maven.selenium.qunit/QUnitTest)/_Query_timeout_tests_/'><strong>[Query timeout tests (single repository)] - Test timeouts for Aloha.RepositoryManager.query method(com.gentics.testutils.maven.selenium.qunit.QUnitTest).[Query timeout tests </strong></a></li></ul>
Test FAILed.

**Comment by Jotschi** [comment]
@GenticsDev please test

**Comment by GenticsDev** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.office:8080//job/alohaeditor-upstream-pullrequests/280/
Test PASSed.

**Pull request merged**
