### PR TITLE
Add new Jenkinsfile and Jenkinsfile-gitlab for Jenkins Pipeline building

### PR DESCRIPTION
**Pull request by berni2288**

### CODE REVIEW

**Comment by berni2288** [comment]
buildnow

**Comment by berni2288** [comment]
buildnow

**Comment by berni2288** [comment]
buildnow

**Comment by berni2288** [comment]
buildnow

**Comment by berni2288** [comment]
buildnow

**Comment by Jotschi** [comment]
LGTM - Verify that the new build works with GCN. I can merge the PR once that has been verified.

**Comment by berni2288** [comment]
already verified, confirmed working. Please proceed the review procedure.

**Pull request merged**
